# SwiftLint Configuration
# Optional linting configuration for code quality

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - operator_usage_whitespace

excluded:
  - Pods
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 150
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y

reporter: "xcode"
